#!/usr/bin/env python3
"""
VS Code 扩展生成工具

将插件转换为完整的 VS Code 扩展（package.json + extension.js + README）。

用法:
    python3 scripts/vscode_extension.py <插件目录> --output ./vscode-extension
    python3 scripts/vscode_extension.py <插件目录> --publisher my-publisher
    python3 scripts/vscode_extension.py <插件目录> --json
"""
import argparse
import json
import sys
from pathlib import Path


def generate_extension_package_json(plugin: dict, publisher: str) -> dict:
    """生成 VS Code 扩展的 package.json"""
    plugin_name = plugin.get("name", "my-extension")
    extension_name = plugin_name.replace(".", "-")

    return {
        "name": extension_name,
        "displayName": plugin.get("description", plugin_name),
        "description": plugin.get("description", ""),
        "version": plugin.get("version", "0.1.0"),
        "publisher": publisher,
        "engines": {"vscode": "^1.80.0"},
        "categories": ["Other"],
        "keywords": ["mcp", "agent", "plugin"],
        "activationEvents": ["onStartupFinished"],
        "main": "./extension.js",
        "contributes": {
            "mcp": {
                "servers": []
            }
        },
        "scripts": {
            "vscode:prepublish": "npm run compile",
            "compile": "echo 'No compilation needed'",
            "watch": "echo 'No watch needed'"
        },
        "devDependencies": {
            "@types/vscode": "^1.80.0",
            "@types/node": "^20.0.0"
        }
    }


def generate_extension_js(plugin: dict) -> str:
    """生成 extension.js"""
    mcp_servers = []
    plugin_dir_name = plugin.get("name", "plugin")

    return f"""// VS Code Extension for {plugin.get('name', 'plugin')}
// Auto-generated by agent-plugin-creator

const vscode = require('vscode');
const path = require('path');

let mcpClient = null;

function activate(context) {{
    console.log('Activating {plugin.get('name', 'plugin')} extension');

    // 注册 MCP 服务器
    const mcpServers = vscode.workspace.getConfiguration('mcp').get('servers', {{}});

    // 在此配置 MCP 服务器
    // 参考: https://code.visualstudio.com/docs/copilot/agent-plugins

    context.subscriptions.push(
        vscode.commands.registerCommand('{plugin.get('name', 'plugin')}.hello', () => {{
            vscode.window.showInformationMessage('{plugin.get('name', 'plugin')} is active!');
        }})
    );
}}

function deactivate() {{
    if (mcpClient) {{
        mcpClient.stop();
    }}
}}

module.exports = {{ activate, deactivate }};
"""


def generate_readme(plugin: dict) -> str:
    """生成 VS Code 扩展的 README"""
    return f"""# {plugin.get('name', 'My Extension')}

{plugin.get('description', '')}

## 功能特性

- MCP 服务器集成
- Agent Plugin 支持
- 多客户端兼容

## 安装

1. 打开 VS Code
2. 按 `Ctrl+Shift+X` 打开扩展面板
3. 搜索 `{plugin.get('name', 'extension')}`
4. 点击安装

## 使用

安装后，扩展会自动激活。MCP 服务器将在 VS Code Copilot Chat 中可用。

## 配置

在 `settings.json` 中配置 MCP 服务器：

```json
{{
  "mcp.servers": {{
    "{plugin.get('name', 'server')}": {{
      "command": "python3",
      "args": ["./servers/server.py"],
      "cwd": "${{workspaceFolder}}"
    }}
  }}
}}
```

## 许可证

MIT
"""


def main():
    parser = argparse.ArgumentParser(description="VS Code 扩展生成工具")
    parser.add_argument("plugin_dir", help="插件目录路径")
    parser.add_argument("--output", help="输出目录（默认 <插件名>-vscode）")
    parser.add_argument("--publisher", default="your-publisher", help="VS Code 发布者名称")
    parser.add_argument("--json", action="store_true", help="JSON 格式输出")
    parser.add_argument("--force", action="store_true", help="覆盖已有文件")
    args = parser.parse_args()

    plugin_dir = Path(args.plugin_dir).resolve()
    if not plugin_dir.is_dir():
        print(f"错误: 插件目录不存在: {plugin_dir}", file=sys.stderr)
        sys.exit(1)

    plugin_json = plugin_dir / "plugin.json"
    if not plugin_json.exists():
        print("错误: 缺少 plugin.json", file=sys.stderr)
        sys.exit(1)

    try:
        plugin = json.loads(plugin_json.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"错误: plugin.json 不是有效 JSON: {e}", file=sys.stderr)
        sys.exit(1)

    output_dir = Path(args.output).resolve() if args.output else plugin_dir.parent / f"{plugin.get('name', 'extension')}-vscode"
    output_dir.mkdir(parents=True, exist_ok=True)

    generated = []

    # package.json
    pkg_path = output_dir / "package.json"
    if not pkg_path.exists() or args.force:
        pkg = generate_extension_package_json(plugin, args.publisher)
        pkg_path.write_text(json.dumps(pkg, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        generated.append("package.json")

    # extension.js
    ext_path = output_dir / "extension.js"
    if not ext_path.exists() or args.force:
        ext_path.write_text(generate_extension_js(plugin), encoding="utf-8")
        generated.append("extension.js")

    # README.md
    readme_path = output_dir / "README.md"
    if not readme_path.exists() or args.force:
        readme_path.write_text(generate_readme(plugin), encoding="utf-8")
        generated.append("README.md")

    # .vscodeignore
    ignore_path = output_dir / ".vscodeignore"
    if not ignore_path.exists() or args.force:
        ignore_path.write_text(".vscode/**\n.vscode-test/**\nsrc/**\n*.map\n", encoding="utf-8")
        generated.append(".vscodeignore")

    # 复制 MCP 服务器代码
    servers_dir = plugin_dir / "servers"
    if servers_dir.exists():
        dest_servers = output_dir / "servers"
        if not dest_servers.exists() or args.force:
            import shutil
            if dest_servers.exists():
                shutil.rmtree(dest_servers)
            shutil.copytree(servers_dir, dest_servers)
            generated.append("servers/")

    result = {
        "extension": plugin.get("name", "extension"),
        "publisher": args.publisher,
        "output": str(output_dir),
        "generated": generated,
    }

    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print("=" * 50)
        print("VS Code 扩展生成完成")
        print("=" * 50)
        print(f"扩展: {plugin.get('name', 'extension')}")
        print(f"发布者: {args.publisher}")
        print(f"输出: {output_dir}")
        print()
        print("生成的文件:")
        for f in generated:
            print(f"  ✅ {f}")
        print()
        print("打包发布:")
        print(f"  cd {output_dir}")
        print("  npm install -g @vscode/vsce")
        print("  vsce package")
        print("  vsce publish")
        print("=" * 50)

    sys.exit(0)


if __name__ == "__main__":
    main()
